// packages/react/src/App.js
import "./App.css";
import {
  AnyCheckbox,
  AnyDropdown,
  AnyListbox,
  AnyButton,
  AnyTabView,
  AnyTabPanel,
  AnyInputText,
} from "@anywhere-ui/react";

function App() {
  const cities = [
    {
      label: "New York",
      value: {
        id: 1,
        name: "New York",
        code: "NY",
        countryCode: "US",
        country: "USA",
      },
    },
    {
      label: "Rome",
      value: {
        id: 2,
        name: "Rome",
        code: "RM",
        countryCode: "IT",
        country: "Italy",
      },
    },
    {
      label: "London",
      value: {
        id: 3,
        name: "London",
        code: "LDN",
        countryCode: "GB",
        country: "England",
      },
    },
    {
      label: "Istanbul",
      value: {
        id: 4,
        name: "Istanbul",
        code: "IST",
        countryCode: "TR",
        country: "Turkey",
      },
    },
    {
      label: "Paris",
      value: {
        id: 5,
        name: "Paris",
        code: "PRS",
        countryCode: "FR",
        country: "France",
      },
    },
    {
      label: "Belgrade",
      value: {
        id: 6,
        name: "Belgrade",
        code: "BGD",
        countryCode: "RS",
        country: "Serbia",
      },
    },
    {
      label: "Tokyo",
      value: {
        id: 7,
        name: "Tokyo",
        code: "TOK",
        countryCode: "JP",
        country: "Japan",
      },
    },
    {
      label: "Madrid",
      value: {
        id: 8,
        name: "Madrid",
        code: "MAD",
        countryCode: "ES",
        country: "Spain",
      },
    },
  ];

  return (
    <div className="App">
      <main>
        <AnyTabView id="tv1">
          <AnyTabPanel header="Header 1">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
          </AnyTabPanel>
          <AnyTabPanel header="Header 2">
            <p>
              Sed ut perspiciatis unde omnis iste natus error sit voluptatem
              accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
              quae ab illo inventore veritatis et quasi architecto beatae vitae
              dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit
              aspernatur aut odit aut fugit, sed quia consequuntur magni dolores
              eos qui ratione voluptatem sequi nesciunt. Consectetur, adipisci
              velit, sed quia non numquam eius modi.
            </p>
          </AnyTabPanel>
          <AnyTabPanel header="Header 3">
            <p>
              At vero eos et accusamus et iusto odio dignissimos ducimus qui
              blanditiis praesentium voluptatum deleniti atque corrupti quos
              dolores et quas molestias excepturi sint occaecati cupiditate non
              provident, similique sunt in culpa qui officia deserunt mollitia
              animi, id est laborum et dolorum fuga. Et harum quidem rerum
              facilis est et expedita distinctio. Nam libero tempore, cum soluta
              nobis est eligendi optio cumque nihil impedit quo minus.
            </p>
          </AnyTabPanel>
        </AnyTabView>
        <AnyCheckbox checked="true" label="React" value="React" /> <br />
        <AnyCheckbox checked="false" label="Vue" value="Vue" /> <br />
        <AnyCheckbox
          checked="true"
          label="Angular"
          value="Angular"
          readonly="false"
        />
        <br />
        <AnyDropdown options={cities} placeholder="Select city" />
        <br />
        <AnyListbox options={cities} anyStyle={{ width: "14rem" }} />
        <br />
        <AnyInputText />
        <br />
        <AnyButton type="submit" label="Submit" />
      </main>
    </div>
  );
}

export default App;

// packages/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'anywhere-ui-angular-test';
  // public selectedCities: number;
  public selectedCityLb: any;
  public selectedCity: any = {
    id: 1,
    name: 'New York',
    code: 'NY',
    countryCode: 'US',
    country: 'USA',
  };

  constructor() {
    setTimeout(() => {
      this.selectedCity = {
        id: 4,
        name: 'Istanbul',
        code: 'IST',
        countryCode: 'TR',
        country: 'Turkey',
      };
      this.selectedCityLb = {
        id: 4,
        name: 'Istanbul',
        code: 'IST',
        countryCode: 'TR',
        country: 'Turkey',
      };
    }, 3000);
  }

  public form = [
    { name: 'pepperoni', val: 'Pepperoni', isChecked: true },
    { name: 'sausage', val: 'Sausage', isChecked: false },
    { name: 'mushroom', val: 'Mushroom', isChecked: false },
  ];

  public cities = [
    {
      label: 'New York',
      value: {
        id: 1,
        name: 'New York',
        code: 'NY',
        countryCode: 'US',
        country: 'USA',
      },
    },
    {
      label: 'Rome',
      value: {
        id: 2,
        name: 'Rome',
        code: 'RM',
        countryCode: 'IT',
        country: 'Italy',
      },
    },
    {
      label: 'London',
      value: {
        id: 3,
        name: 'London',
        code: 'LDN',
        countryCode: 'GB',
        country: 'England',
      },
    },
    {
      label: 'Istanbul',
      value: {
        id: 4,
        name: 'Istanbul',
        code: 'IST',
        countryCode: 'TR',
        country: 'Turkey',
      },
    },
    {
      label: 'Paris',
      value: {
        id: 5,
        name: 'Paris',
        code: 'PRS',
        countryCode: 'FR',
        country: 'France',
      },
    },
    {
      label: 'Belgrade',
      value: {
        id: 6,
        name: 'Belgrade',
        code: 'BGD',
        countryCode: 'RS',
        country: 'Serbia',
      },
    },
    {
      label: 'Tokyo',
      value: {
        id: 7,
        name: 'Tokyo',
        code: 'TOK',
        countryCode: 'JP',
        country: 'Japan',
      },
    },
    {
      label: 'Madrid',
      value: {
        id: 8,
        name: 'Madrid',
        code: 'MAD',
        countryCode: 'ES',
        country: 'Spain',
      },
    },
  ];
  // public citiesLb = [...this.cities];

  checkEvent(val: any) {
    console.log(val);
  }

  onSubmit(data: any) {
    console.log(data);
  }
}

<!-- <router-outlet></router-outlet> -->

<any-tab-view id="tv1">
  <any-tab-panel header="Header 1">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
      magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
      ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </any-tab-panel>
  <any-tab-panel header="Header 2">
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
      aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
      architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit
      aut fugit, sed quia consequuntur magni dolores eos qui ratione
      voluptatem sequi nesciunt. Consectetur, adipisci velit, sed quia non numquam eius modi.</p>
  </any-tab-panel>
  <any-tab-panel header="Header 3">
    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti
      atque corrupti quos dolores et quas molestias excepturi sint occaecati
      cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et
      dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.
      Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus.</p>
  </any-tab-panel>
</any-tab-view>

<form #newUserForm="ngForm" (ngSubmit)="onSubmit(newUserForm)">
  <div *ngFor="let entry of form; let i=index" style="margin-top: 10px;">
    <any-checkbox [name]="'checkbox_' + entry.name" (ngModelChange)="checkEvent($event)" [label]="entry.val"
      [value]="entry.val" [(ngModel)]="entry.isChecked" [checked]="entry.isChecked">
    </any-checkbox>
  </div>

  <div>{{form | json}}</div><br><br><br><br>
  <any-dropdown name="test" [options]="cities" placeholder="Select City" showClear="true"
    (ngModelChange)="checkEvent($event)" [(ngModel)]="selectedCity">
  </any-dropdown>
  <div>{{selectedCity | json}}</div><br><br>
  <any-listbox [anyStyle]="{width: '14rem'}" name="testLb" [options]="cities" (ngModelChange)="checkEvent($event)"
    [(ngModel)]="selectedCityLb">
  </any-listbox>
  <div>{{selectedCityLb | json}}</div><br><br>
  <any-input-text id="it1"></any-input-text><br><br>

  <any-button type="submit" label="Save"></any-button><br><br>

</form>
